/**
 * Seeded Merchant Category Code reference data for getAllMerchantCategoryCodes (design §2: "getAllProducts
 * and getAllMerchantCategoryCodes return seeded reference data"). The spec and docs carry no list
 * (docs/map/stubs.md), so this is a static selection of common ISO 18245 codes, ascending, with their
 * usual scheme descriptions; the codes are the integers MERCHANT_CODE_BLOCK rules take.
 */
export interface MerchantCategoryCode { code: number; description: string }

export const MERCHANT_CATEGORY_CODES: readonly MerchantCategoryCode[] = [
  { code: 1520, description: 'General Contractors - Residential and Commercial' },
  { code: 1711, description: 'Heating, Plumbing, and Air Conditioning Contractors' },
  { code: 1731, description: 'Electrical Contractors' },
  { code: 1799, description: 'Special Trade Contractors (Not Elsewhere Classified)' },
  { code: 2741, description: 'Miscellaneous Publishing and Printing' },
  { code: 4011, description: 'Railroads' },
  { code: 4111, description: 'Local and Suburban Commuter Passenger Transportation, including Ferries' },
  { code: 4112, description: 'Passenger Railways' },
  { code: 4121, description: 'Taxicabs and Limousines' },
  { code: 4131, description: 'Bus Lines' },
  { code: 4214, description: 'Motor Freight Carriers and Trucking' },
  { code: 4215, description: 'Courier Services - Air and Ground, and Freight Forwarders' },
  { code: 4411, description: 'Steamship and Cruise Lines' },
  { code: 4511, description: 'Airlines and Air Carriers' },
  { code: 4722, description: 'Travel Agencies and Tour Operators' },
  { code: 4784, description: 'Tolls and Bridge Fees' },
  { code: 4812, description: 'Telecommunication Equipment and Telephone Sales' },
  { code: 4814, description: 'Telecommunication Services' },
  { code: 4816, description: 'Computer Network and Information Services' },
  { code: 4829, description: 'Wire Transfers and Money Orders' },
  { code: 4899, description: 'Cable, Satellite and Other Pay Television and Radio Services' },
  { code: 4900, description: 'Utilities - Electric, Gas, Water and Sanitary' },
  { code: 5045, description: 'Computers, Computer Peripheral Equipment and Software' },
  { code: 5094, description: 'Precious Stones and Metals, Watches and Jewellery' },
  { code: 5111, description: 'Stationery, Office Supplies, Printing and Writing Paper' },
  { code: 5122, description: 'Drugs, Drug Proprietaries and Druggists Sundries' },
  { code: 5200, description: 'Home Supply Warehouse Stores' },
  { code: 5211, description: 'Lumber and Building Materials Stores' },
  { code: 5251, description: 'Hardware Stores' },
  { code: 5261, description: 'Nurseries and Lawn and Garden Supply Stores' },
  { code: 5300, description: 'Wholesale Clubs' },
  { code: 5310, description: 'Discount Stores' },
  { code: 5311, description: 'Department Stores' },
  { code: 5331, description: 'Variety Stores' },
  { code: 5399, description: 'Miscellaneous General Merchandise' },
  { code: 5411, description: 'Grocery Stores, Supermarkets' },
  { code: 5422, description: 'Freezer and Locker Meat Provisioners' },
  { code: 5441, description: 'Candy, Nut and Confectionery Stores' },
  { code: 5451, description: 'Dairy Products Stores' },
  { code: 5462, description: 'Bakeries' },
  { code: 5499, description: 'Miscellaneous Food Stores - Convenience Stores and Specialty Markets' },
  { code: 5511, description: 'Car and Truck Dealers (New and Used) - Sales, Service, Repairs, Parts and Leasing' },
  { code: 5532, description: 'Automotive Tyre Stores' },
  { code: 5533, description: 'Automotive Parts and Accessories Stores' },
  { code: 5541, description: 'Service Stations (with or without Ancillary Services)' },
  { code: 5542, description: 'Automated Fuel Dispensers' },
  { code: 5611, description: "Men's and Boys' Clothing and Accessories Stores" },
  { code: 5621, description: "Women's Ready-to-Wear Stores" },
  { code: 5641, description: "Children's and Infants' Wear Stores" },
  { code: 5651, description: 'Family Clothing Stores' },
  { code: 5661, description: 'Shoe Stores' },
  { code: 5691, description: "Men's and Women's Clothing Stores" },
  { code: 5712, description: 'Furniture, Home Furnishings and Equipment Stores, except Appliances' },
  { code: 5722, description: 'Household Appliance Stores' },
  { code: 5732, description: 'Electronics Stores' },
  { code: 5733, description: 'Music Stores - Musical Instruments, Pianos and Sheet Music' },
  { code: 5734, description: 'Computer Software Stores' },
  { code: 5735, description: 'Record Stores' },
  { code: 5811, description: 'Caterers' },
  { code: 5812, description: 'Eating Places, Restaurants' },
  { code: 5813, description: 'Drinking Places (Alcoholic Beverages) - Bars, Taverns, Nightclubs' },
  { code: 5814, description: 'Fast Food Restaurants' },
  { code: 5815, description: 'Digital Goods - Media: Books, Movies, Music' },
  { code: 5816, description: 'Digital Goods - Games' },
  { code: 5817, description: 'Digital Goods - Applications (excludes Games)' },
  { code: 5818, description: 'Digital Goods - Large Digital Goods Merchant' },
  { code: 5912, description: 'Drug Stores and Pharmacies' },
  { code: 5921, description: 'Package Stores - Beer, Wine and Liquor' },
  { code: 5941, description: 'Sporting Goods Stores' },
  { code: 5942, description: 'Book Stores' },
  { code: 5943, description: 'Stationery, Office and School Supply Stores' },
  { code: 5944, description: 'Jewellery, Watch, Clock and Silverware Stores' },
  { code: 5945, description: 'Hobby, Toy and Game Shops' },
  { code: 5947, description: 'Gift, Card, Novelty and Souvenir Shops' },
  { code: 5977, description: 'Cosmetic Stores' },
  { code: 5992, description: 'Florists' },
  { code: 5995, description: 'Pet Shops, Pet Food and Supplies Stores' },
  { code: 5999, description: 'Miscellaneous and Specialty Retail Stores' },
  { code: 6010, description: 'Financial Institutions - Manual Cash Disbursements' },
  { code: 6011, description: 'Financial Institutions - Automated Cash Disbursements' },
  { code: 6012, description: 'Financial Institutions - Merchandise, Services and Debt Repayment' },
  { code: 6051, description: 'Non-Financial Institutions - Foreign Currency, Money Orders, Travellers Cheques' },
  { code: 6211, description: 'Security Brokers and Dealers' },
  { code: 6300, description: 'Insurance Sales, Underwriting and Premiums' },
  { code: 6513, description: 'Real Estate Agents and Managers - Rentals' },
  { code: 6540, description: 'Non-Financial Institutions - Stored Value Card Purchase and Load' },
  { code: 7011, description: 'Lodging - Hotels, Motels and Resorts' },
  { code: 7210, description: 'Laundry, Cleaning and Garment Services' },
  { code: 7230, description: 'Beauty and Barber Shops' },
  { code: 7298, description: 'Health and Beauty Spas' },
  { code: 7299, description: 'Miscellaneous Personal Services (Not Elsewhere Classified)' },
  { code: 7311, description: 'Advertising Services' },
  { code: 7372, description: 'Computer Programming, Data Processing and Integrated Systems Design Services' },
  { code: 7399, description: 'Business Services (Not Elsewhere Classified)' },
  { code: 7512, description: 'Car Rental Agencies' },
  { code: 7523, description: 'Parking Lots, Parking Meters and Garages' },
  { code: 7538, description: 'Automotive Service Shops (Non-Dealer)' },
  { code: 7542, description: 'Car Washes' },
  { code: 7832, description: 'Motion Picture Theatres' },
  { code: 7841, description: 'Video Tape Rental Stores' },
  { code: 7922, description: 'Theatrical Producers (except Motion Pictures) and Ticket Agencies' },
  { code: 7941, description: 'Commercial Sports, Professional Sports Clubs, Athletic Fields and Sports Promoters' },
  { code: 7991, description: 'Tourist Attractions and Exhibits' },
  { code: 7995, description: 'Betting, including Lottery Tickets, Casino Gaming Chips and Wagers at Race Tracks' },
  { code: 7997, description: 'Membership Clubs (Sports, Recreation, Athletic), Country Clubs and Private Golf Courses' },
  { code: 7999, description: 'Recreation Services (Not Elsewhere Classified)' },
  { code: 8011, description: 'Doctors and Physicians (Not Elsewhere Classified)' },
  { code: 8021, description: 'Dentists and Orthodontists' },
  { code: 8043, description: 'Opticians, Optical Goods and Eyeglasses' },
  { code: 8062, description: 'Hospitals' },
  { code: 8099, description: 'Medical Services and Health Practitioners (Not Elsewhere Classified)' },
  { code: 8111, description: 'Legal Services and Attorneys' },
  { code: 8211, description: 'Elementary and Secondary Schools' },
  { code: 8220, description: 'Colleges, Universities, Professional Schools and Junior Colleges' },
  { code: 8299, description: 'Schools and Educational Services (Not Elsewhere Classified)' },
  { code: 8398, description: 'Charitable and Social Service Organisations' },
  { code: 8641, description: 'Civic, Social and Fraternal Associations' },
  { code: 8651, description: 'Political Organisations' },
  { code: 8661, description: 'Religious Organisations' },
  { code: 8931, description: 'Accounting, Auditing and Bookkeeping Services' },
  { code: 8999, description: 'Professional Services (Not Elsewhere Classified)' },
  { code: 9211, description: 'Court Costs, including Alimony and Child Support' },
  { code: 9222, description: 'Fines' },
  { code: 9311, description: 'Tax Payments' },
  { code: 9399, description: 'Government Services (Not Elsewhere Classified)' },
  { code: 9402, description: 'Postal Services - Government Only' },
]
