/**
 * Regenerates the implementation-progress block at the top of README.md from the live route table:
 * an operation counts as implemented when a domain module handles it (i.e. it is not served by the
 * generic stub). Run: npm run progress  (also run by .githooks/pre-commit on main).
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { execSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import { buildServer } from '../src/server.js'
import { operations } from '../src/contract/index.js'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const README = path.join(ROOT, 'README.md')
const START = '<!-- progress:start -->'
const END = '<!-- progress:end -->'

/** Sections that are stub-only by design (spec-shaped deterministic responses, no state). */
const STUB_ONLY = new Set(['Perks API', 'FX API', 'Liquidity API', 'Click to Pay API', 'Tokens API', 'Merchant Category Codes API'])

const { app, stubbed } = await buildServer({ logLevel: 'silent', auth: false })
await app.ready()
const stubSet = new Set(stubbed)
await app.close()

interface Row { tag: string; total: number; done: number; stubOnly: boolean }
const rows = new Map<string, Row>()
for (const op of operations) {
  const r = rows.get(op.tag) ?? { tag: op.tag, total: 0, done: 0, stubOnly: STUB_ONLY.has(op.tag) }
  r.total++
  if (!stubSet.has(op.operationId)) r.done++
  rows.set(op.tag, r)
}
const full = [...rows.values()].filter((r) => !r.stubOnly).sort((a, b) => a.tag.localeCompare(b.tag))
const stubs = [...rows.values()].filter((r) => r.stubOnly).sort((a, b) => a.tag.localeCompare(b.tag))
const inScopeTotal = full.reduce((n, r) => n + r.total, 0)
const inScopeDone = full.reduce((n, r) => n + r.done, 0)
const stubTotal = stubs.reduce((n, r) => n + r.total, 0)
const pct = (d: number, t: number) => (t ? Math.round((100 * d) / t) : 0)
const bar = (p: number) => '█'.repeat(Math.round(p / 5)) + '░'.repeat(20 - Math.round(p / 5))
const status = (r: Row) => (r.done === r.total ? '✅ complete' : r.done === 0 ? '⬜ not started' : '🟡 in progress')

let tests = ''
try {
  tests = `Test files: ${execSync('ls test/*.test.ts | wc -l', { cwd: ROOT }).toString().trim()}`
} catch { /* ignore */ }
const commit = (() => { try { return execSync('git rev-parse --short HEAD', { cwd: ROOT }).toString().trim() } catch { return 'unknown' } })()
const date = new Date().toISOString().slice(0, 10)

const lines: string[] = []
lines.push(START)
lines.push('## Implementation progress')
lines.push('')
lines.push(`**Full-fidelity operations: ${inScopeDone} / ${inScopeTotal} (${pct(inScopeDone, inScopeTotal)}%)**  \`${bar(pct(inScopeDone, inScopeTotal))}\``)
lines.push('')
lines.push(`All ${operations.length} operations of the spec are routed and schema-validated; the ${stubTotal} stub-only operations answer with deterministic spec-shaped data. ${tests ? tests + '. ' : ''}Updated ${date} at \`${commit}\`.`)
lines.push('')
lines.push('| Section | Implemented | Progress | Status |')
lines.push('|---|---|---|---|')
for (const r of full) lines.push(`| ${r.tag} | ${r.done} / ${r.total} | \`${bar(pct(r.done, r.total))}\` ${pct(r.done, r.total)}% | ${status(r)} |`)
for (const r of stubs) lines.push(`| ${r.tag} | stub-only | \`${bar(100)}\` 100% | ✅ stub (by design) |`)
lines.push('')
lines.push('_Generated by `npm run progress` from the live route table (implemented = handled by a domain module, not the generic stub)._')
lines.push(END)
const block = lines.join('\n')

let readme = readFileSync(README, 'utf8')
if (readme.includes(START) && readme.includes(END)) {
  readme = readme.slice(0, readme.indexOf(START)) + block + readme.slice(readme.indexOf(END) + END.length)
} else {
  const firstBlank = readme.indexOf('\n\n')
  readme = readme.slice(0, firstBlank + 2) + block + '\n\n' + readme.slice(firstBlank + 2)
}
writeFileSync(README, readme)
console.log(`progress: ${inScopeDone}/${inScopeTotal} full-fidelity operations implemented (${pct(inScopeDone, inScopeTotal)}%)`)
